### ISSUE TITLE
Android.Views.InflateException

### ISSUE THREAD

**Issue by cocoretch** [jamesmontemagno/CircleImageView-Xamarin.Android#10]
When I m trying to run I am getting this error on SetContentView. Interesting side is sometimes it runs and I can see my circle images but most of the time I am getting this error

Unhandled Exception:
Android.Views.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class refractored.controls.CircleImageView occurred

<refractored.controls.CircleImageView
        android:layout_width="30dp"
        android:layout_height="30dp"
        android:src="@drawable/loginIcon"/>

**Comment by db2222** [comment]
I have exactly the same problem. I have setup a new environment with Visual Studio 2019 (16.1.3) and the issue now constantly appears. Usually it resolved itself via Clean Solution, Rebuild, Restarting the emulator, Restart Visual Studio etc. but here absolutely nothing fixes it.

I do not have the problem in other environments?!

What could be the reason?

Thanks.

**Comment by wayousuf** [comment]
Having the same issue, is there any fix or alternative of it?

**Comment by cocoretch** [comment]
I couldn't find for now if you wait couple mins it fixes by itself or close & open visual studio fixes for one time. maybe downgrade works I didnt try if you tried is it works do you know?

**Comment by wayousuf** [comment]
you can either downgrade or make a release dll of CircleImageView project and reference it into your android project directly, both work for me.

**Comment by eclipsed4utoo** [comment]
Getting the same error :(

**Comment by hassanbht** [comment]
same issue

**Comment by dharmik** [comment]
I am also facing that same issue.

**Comment by SharpMobileCode** [comment]
Same error here.  Started happening when I upgraded to the latest VS for Mac and Xamarin.Android. 
 Here's my stacktrace:
```
Android.Views.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class refractored.controls.CircleImageView ---> Android.Views.InflateException: Binary XML file line #1: Error inflating class refractored.controls.CircleImageView ---> Java.Lang.ClassNotFoundException: Didn't find class "refractored.controls.CircleImageView" on path: DexPathList[[zip file "/data/app/com.mycompany.myapp-JtpeyD7IPE11PQ32Ku-Hcg==/base.apk"],nativeLibraryDirectories=[/data/app/com.mycompany.myapp-JtpeyD7IPE11PQ32Ku-Hcg==/lib/x86, /data/app/com.mycompany.myapp-JtpeyD7IPE11PQ32Ku-Hcg==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]
  at java.lang.ClassNotFoundException: Didn't find class "refractored.controls.CircleImageView" on path: DexPathList[[zip file "/data/app/com.mycompany.myapp-JtpeyD7IPE11PQ32Ku-Hcg==/base.apk"],nativeLibraryDirectories=[/data/app/com.mycompany.myapp-JtpeyD7IPE11PQ32Ku-Hcg==/lib/x86, /data/app/com.mycompany.myapp-JtpeyD7IPE11PQ32Ku-Hcg==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]
  at at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
  at at android.view.LayoutInflater.createView(LayoutInflater.java:606)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
  at at mvvmcross.binding.droid.views.MvxLayoutInflater.n_inflate(Native Method)
  at at mvvmcross.binding.droid.views.MvxLayoutInflater.inflate(MvxLayoutInflater.java:50)
  at at android.support.design.internal.NavigationMenuPresenter.inflateHeaderView(NavigationMenuPresenter.java:207)
  at at android.support.design.widget.NavigationView.inflateHeaderView(NavigationView.java:281)
  at at android.support.design.widget.NavigationView.<init>(NavigationView.java:193)
  at at android.support.design.widget.NavigationView.<init>(NavigationView.java:104)
  at at java.lang.reflect.Constructor.newInstance0(Native Method)
  at at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
  at at android.view.LayoutInflater.createView(LayoutInflater.java:647)
  at at mvvmcross.binding.droid.views.MvxLayoutInflater_PrivateFactoryWrapper2.n_onCreateView(Native Method)
  at at mvvmcross.binding.droid.views.MvxLayoutInflater_PrivateFactoryWrapper2.onCreateView(MvxLayoutInflater_PrivateFactoryWrapper2.java:32)
  at at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
  at at com.mycompany.myapp.MainActivity.n_onCreate(Native Method)
  at at com.mycompany.myapp.MainActivity.onCreate(MainActivity.java:57)
  at at android.app.Activity.performCreate(Activity.java:6975)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
  at at android.app.ActivityThread.-wrap11(Unknown Source:0)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
  at at android.os.Handler.dispatchMessage(Handler.java:105)
  at at android.os.Looper.loop(Looper.java:164)
  at at android.app.ActivityThread.main(ActivityThread.java:6541)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
  --- End of inner exception stack trace ---
  at android.view.InflateException: Binary XML file line #1: Error inflating class refractored.controls.CircleImageView
  at Caused by: java.lang.ClassNotFoundException: Didn't find class "refractored.controls.CircleImageView" on path: DexPathList[[zip file "/data/app/com.mycompany.myapp-JtpeyD7IPE11PQ32Ku-Hcg==/base.apk"],nativeLibraryDirectories=[/data/app/com.mycompany.myapp-JtpeyD7IPE11PQ32Ku-Hcg==/lib/x86, /data/app/com.mycompany.myapp-JtpeyD7IPE11PQ32Ku-Hcg==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]
  at at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
  at at android.view.LayoutInflater.createView(LayoutInflater.java:606)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
  at at mvvmcross.binding.droid.views.MvxLayoutInflater.n_inflate(Native Method)
  at at mvvmcross.binding.droid.views.MvxLayoutInflater.inflate(MvxLayoutInflater.java:50)
  at at android.support.design.internal.NavigationMenuPresenter.inflateHeaderView(NavigationMenuPresenter.java:207)
  at at android.support.design.widget.NavigationView.inflateHeaderView(NavigationView.java:281)
  at at android.support.design.widget.NavigationView.<init>(NavigationView.java:193)
  at at android.support.design.widget.NavigationView.<init>(NavigationView.java:104)
  at at java.lang.reflect.Constructor.newInstance0(Native Method)
  at at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
  at at android.view.LayoutInflater.createView(LayoutInflater.java:647)
  at at mvvmcross.binding.droid.views.MvxLayoutInflater_PrivateFactoryWrapper2.n_onCreateView(Native Method)
  at at mvvmcross.binding.droid.views.MvxLayoutInflater_PrivateFactoryWrapper2.onCreateView(MvxLayoutInflater_PrivateFactoryWrapper2.java:32)
  at at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
  at at com.mycompany.myapp.MainActivity.n_onCreate(Native Method)
  at at com.mycompany.myapp.MainActivity.onCreate(MainActivity.java:57)
  at at android.app.Activity.performCreate(Activity.java:6975)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
  at at android.app.ActivityThread.-wrap11(Unknown Source:0)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
  at at android.os.Handler.dispatchMessage(Handler.java:105)
  at at android.os.Looper.loop(Looper.java:164)
  at at android.app.ActivityThread.main(ActivityThread.java:6541)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
  --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <3beddfcb1eb547cd8ce47c3097f6eaeb>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <3beddfcb1eb547cd8ce47c3097f6eaeb>:0
  at Android.Views.LayoutInflater.Inflate (System.Int32 resource, Android.Views.ViewGroup root, System.Boolean attachToRoot) [0x0005a] in <ff9f3f3d4e134974a889db1b532c9b6e>:0
  at MvvmCross.Binding.Droid.Views.MvxLayoutInflater.Inflate (System.Int32 resource, Android.Views.ViewGroup root, System.Boolean attachToRoot) [0x0003e] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\Views\MvxLayoutInflater.cs:137
  at Android.Views.LayoutInflater.n_Inflate_ILandroid_view_ViewGroup_Z (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 resource, System.IntPtr native_root, System.Boolean attachToRoot) [0x00011] in <ff9f3f3d4e134974a889db1b532c9b6e>:0
  at at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.41(intptr,intptr,int,intptr,bool)
  at android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class refractored.controls.CircleImageView
  at Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class refractored.controls.CircleImageView
  at Caused by: java.lang.ClassNotFoundException: Didn't find class "refractored.controls.CircleImageView" on path: DexPathList[[zip file "/data/app/com.mycompany.myapp-JtpeyD7IPE11PQ32Ku-Hcg==/base.apk"],nativeLibraryDirectories=[/data/app/com.mycompany.myapp-JtpeyD7IPE11PQ32Ku-Hcg==/lib/x86, /data/app/com.mycompany.myapp-JtpeyD7IPE11PQ32Ku-Hcg==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]
  at at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
  at at android.view.LayoutInflater.createView(LayoutInflater.java:606)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
  at at mvvmcross.binding.droid.views.MvxLayoutInflater.n_inflate(Native Method)
  at at mvvmcross.binding.droid.views.MvxLayoutInflater.inflate(MvxLayoutInflater.java:50)
  at at android.support.design.internal.NavigationMenuPresenter.inflateHeaderView(NavigationMenuPresenter.java:207)
  at at android.support.design.widget.NavigationView.inflateHeaderView(NavigationView.java:281)
  at at android.support.design.widget.NavigationView.<init>(NavigationView.java:193)
  at at android.support.design.widget.NavigationView.<init>(NavigationView.java:104)
  at at java.lang.reflect.Constructor.newInstance0(Native Method)
  at at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
  at at android.view.LayoutInflater.createView(LayoutInflater.java:647)
  at at mvvmcross.binding.droid.views.MvxLayoutInflater_PrivateFactoryWrapper2.n_onCreateView(Native Method)
  at at mvvmcross.binding.droid.views.MvxLayoutInflater_PrivateFactoryWrapper2.onCreateView(MvxLayoutInflater_PrivateFactoryWrapper2.java:32)
  at at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
  at at com.mycompany.myapp.MainActivity.n_onCreate(Native Method)
  at at com.mycompany.myapp.MainActivity.onCreate(MainActivity.java:57)
  at at android.app.Activity.performCreate(Activity.java:6975)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
  at at android.app.ActivityThread.-wrap11(Unknown Source:0)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
  at at android.os.Handler.dispatchMessage(Handler.java:105)
  at at android.os.Looper.loop(Looper.java:164)
  at at android.app.ActivityThread.main(ActivityThread.java:6541)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

## Environment Info

=== Visual Studio Community 2019 for Mac ===

Version 8.1.3 (build 19)
Installation UUID: e52a2354-265b-4abc-a0dd-dd91eaeb48ff
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

	Package version: 518010028

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
	Package version: 518010028

=== NuGet ===

Version: 5.0.2.5988

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.5
	2.2.0
	2.1.9
	2.1.2
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.2.300/Sdks
SDK Versions:
	2.2.300
	2.2.101
	2.1.505
	2.1.302
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Version: 5.10.0.157 (Visual Studio Community)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:48-0400

=== Xamarin.iOS ===

Version: 12.10.0.157 (Visual Studio Community)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:47-0400

=== Xamarin Designer ===

Version: 16.1.0.467
Hash: f1657e133
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-18 21:57:42 UTC

=== Xamarin.Android ===

Version: 9.3.0.23 (Visual Studio Community)
Commit: HEAD/d0b48056f
Android SDK: /Users/rubenmacias/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.0 (API level 24)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2018-08@3a07bd426d3
Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/rubenmacias/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-29 19:55:24 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 801030019
Git revision: 2d04b0145da8aa946d2cc9898fe2a59484e4f3f4
Build date: 2019-06-26 15:34:25+00
Build branch: release-8.1
Xamarin extensions: de240bddd6d1f96bfb1e7d11ce7ac5398956fe1d

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

MFractor 3.8.9

**Comment by SharpMobileCode** [comment]
More information:

https://developercommunity.visualstudio.com/content/problem/596032/xamarin-android-crushing-on-native-librabries.html

**Comment by jamesmontemagno** [comment]
Hmmmm maybe I need to rev a new version of it... hmmmm

**Comment by jamesmontemagno** [comment]
I am not super sure... I tried to bring in some new stuff. @Redth  any ideas on this... old binding.

**Comment by jamesmontemagno** [comment]
Just uploaded 1.2.0-preview that should fix this. Please take a look

**Comment by SharpMobileCode** [comment]
> Just uploaded 1.2.0-preview that should fix this. Please take a look

I can confirm that 1.2.0-preview fixes the issue.  Thank you so much! 👍

**Comment by jamesmontemagno** [comment]
<3
